name: Build and release
run-name: Build and release gotify-to-ntfy-proxy docker container
on:
  push:
    branches:
      - master

jobs:
  release_build:
    run-on: ubuntu-latest
    steps:
      - # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v4
      - # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - # https://github.com/docker/setup-buildx-action
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - # https://github.com/docker/login-action
        name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      -
        name: Get npm package version for release tag
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      -
        name: Build container and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/amd64/v2,linux/arm64,linux/arm/v8,linux/arm/v7
          push: true
          tags: levantinlynx/gotify-to-ntfy-proxy:latest,levantinlynx/gotify-to-ntfy-proxy:${{ steps.package-version.outputs.current-version }}
      -
        name: Actions Ntfy
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            -H "Tags: package,building_construction" \
            -H "Title: Container Build ${{ job.status }}" \
            -H "Content-Type: text/plain" \
            -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ job.status }}' \
            ${{ secrets.NTFY_URL }}